### ISSUE TITLE
test_framework_version fails on Windows Server 2012 R2

### ISSUE THREAD

**Issue by sneal** [daptiv/dotnetframework#17]
The [version numbers for 4.5.1 and 4.5.2 differ between Windows versions](https://msdn.microsoft.com/en-us/library/hh925568(v=vs.110).aspx). The current versions in the attribute files are for Windows 2008.

# .NET 4.5.1
- Release: 378675
- Version: 4.5.51641

# .NET 4.5.2
- Release: 379893
- Version: 4.5.51650

**Comment by ma7859** [comment]
It fails on Windows Server 2012 R2 with following error:
FATAL: Mixlib::ShellOut::ShellCommandFailed: windows_package[Microsoft .NET Fra
mework 4.5.2] 
Mixlib::ShellOut::ShellCommandFailed: Expected
process to exit with [0, 42,127], but received '3010'

**Comment by sneal** [comment]
Fixed by #19
