### ISSUE TITLE
I am getting file sizes exceed error while running dotnetframework cookbook

### ISSUE THREAD

**Issue by rajeshapt** [daptiv/dotnetframework#33]
I have copied the dotnet exe package to my local shared folder and gave the URL path but the package is copied to the node under chache folder and it shows file sizes exceed 10000000 bytes, diff output suppressed. Not sure if the limit set anywhere in cookbook? and dot net is not getting installed. It only getting copied to the node cache folder. Can someone help please.

**Comment by sneal** [comment]
- What .NET version are you installing?
- What Windows version?
- What's the Chef run output?
- What's the .NET framework installer log file output, if any?

The .NET installer log file will be in your [temp directory named the same as the .NET installer with a .html file extension](https://github.com/daptiv/dotnetframework/blob/b8e0818d2e930dc146616dd5a24bca8a2c6b0587/providers/version.rb#L34).

**Comment by rajeshapt** [comment]
Hi Sneal
It got installed now but windows_reboot didn't work. I use .net 4.6.1 and OS Win 2012R2.
The console was showing the windows_reboot resource is deprecated. Please use the reboot resource in chef client 12.

**Comment by sneal** [comment]
You need to ensure you have the windows::reboot_handler in your run list. The deprecation warning is legitimate, however it doesn't affect functionality.

**Comment by sneal** [comment]
I opened a new issue for the deprecation warning #35
