### ISSUE TITLE
scheduled_task cookbook no longer exists in chef supermarket

### ISSUE THREAD

**Issue by dee3sync** [daptiv/dotnetframework#48]
Trying to run a berks install but the scheduled_task cookbook cannot be found:

![image](https://user-images.githubusercontent.com/14794837/36213401-3ce1165a-116c-11e8-9d9a-fde514e9654d.png)

**Comment by linusruth** [comment]
Thanks for the report.  I've rolled back the repo until I get around to publishing the scheduled_task cookbook.
